from selenium.webdriver.common.by import By

class OrderPageLocators:
    COOKIE_BUTTON = (By.ID, "rcc-confirm-button")
    TOP_ORDER_BUTTON = (By.XPATH, "//button[contains(@class, 'Button_Button')]")
    BOTTOM_ORDER_BUTTON = (By.XPATH, "//div[contains(@class, 'Home_FinishButton')]//button")
    ORDER_HEADER_FIRST_PAGE = (By.XPATH, "//div[contains(@class,'Order_Header') and text()='Для кого самокат']")
    NAME_FIELD = (By.CSS_SELECTOR, "input[placeholder='* Имя']")
    SURNAME_FIELD = (By.CSS_SELECTOR, "input[placeholder='* Фамилия']")
    ADRESS_FIELD = (By.CSS_SELECTOR, "input[placeholder='* Адрес: куда привезти заказ']")
    METRO_FIELD = (By.CSS_SELECTOR, ".select-search__input")
    TELEPHONE_FIELD = (By.CSS_SELECTOR, "input[placeholder='* Телефон: на него позвонит курьер']")
    NEXT_PAGE_BUTTON = (By.CSS_SELECTOR, "button.Button_Middle__1CSJM:nth-child(1)")
    ORDER_HEADER_SECOND_PAGE = (By.XPATH, "//div[contains(@class,'Order_Header') and text()='Про аренду']")
    ORDER_DATE_FIELD = (By.XPATH, "//input[@placeholder='* Когда привезти самокат']")
    RENTAL_PERIOD_FIELD = (By.CSS_SELECTOR, ".Dropdown-placeholder")
    RENTAL_PERIOD_OPTION = (By.CSS_SELECTOR, ".Dropdown-option")
    SCOOTER_COLOR_FIELD = (By.CSS_SELECTOR, ".Order_Checkboxes__3lWSI")
    COMMENT_FIELD = (By.CSS_SELECTOR, "input[placeholder='Комментарий для курьера']")
    ORDER_BUTTON = (By.XPATH, "//div[contains(@class, 'Order_Content')]//button[text()='Заказать']")
    OVERLAY = (By.CLASS_NAME, "Order_Overlay__3KW-T")
    CONFIRM_YES_BUTTON = (By.XPATH, "//button[text()='Да']")
    ORDER_MODAL_HEADER = (By.CSS_SELECTOR, ".Order_ModalHeader__3FDaJ")
    SCOOTER_LOGO_BUTTON = (By.CSS_SELECTOR, ".Header_LogoScooter__3lsAR > img:nth-child(1)")
    YANDEX_LOGO_BUTTON = (By.CSS_SELECTOR, ".Header_LogoYandex__3TSOI > img:nth-child(1)")
